### ISSUE TITLE
Korean & Chinese Romanization

### ISSUE THREAD

**Issue by MetroHospitalsDev** [Patrick-orz/PopupLyrics-Plus#2]
Hello , thankyou for the great extensions.
is there any updates for korean and chinese romanization ?

**Comment by Patrick-orz** [comment]
I am glad you enjoy the extension! I would add this into the to-do list, and would probably work on it after stabilizing english translations :P. Stay tuned!

**Comment by MetroHospitalsDev** [comment]
cant wait for the next features update !
by the way , after i am upgrading to v2.
popuplyrics somehow freezing when changing to next song, with popuplyics only show loading text and spotify media button (play , next ) is freezing.
when i open task manager, it showing spotify using 100% memory and 100% cpu.
is there any memory leaks ?

**Comment by Patrick-orz** [comment]
> cant wait for the next features update ! by the way , after i am upgrading to v2. popuplyrics somehow freezing when changing to next song, with popuplyics only show loading text and spotify media button (play , next ) is freezing. when i open task manager, it showing spotify using 100% memory and 100% cpu. is there any memory leaks ?

I can't seem to reproduce the issue... Can you specify your environment and setup (translating to...) please?
I wonder if this is a consistent issue or one that happens periodically.

**Comment by MetroHospitalsDev** [comment]
im using translating to romanji.
in my case , it happen consistently when spotify not on active windows and spotify changing to next song then the issue will produce. already tried 3 / 4 times and it happen consistently

![Uploading popuplyricsplus.png…]()

**Comment by Patrick-orz** [comment]
Move discussion to #5 
This issue would be focused on Korean & Chinese Romanization

**Comment by frallatta** [comment]
Hello , i add chinese pinyin and aromanize. please check #7

**Comment by Patrick-orz** [comment]
Closed with the merge of #7, thanks again for the contribution!
