### ISSUE TITLE
Spotify freezing with V2

### ISSUE THREAD

**Issue by Patrick-orz** [Patrick-orz/PopupLyrics-Plus#5]
> im using translating to romanji.
in my case , it happen consistently when spotify not on active windows and spotify changing to next song then the issue will produce. already tried 3 / 4 times and it happen consistently

![popuplyricsplus](https://github.com/Patrick-orz/PopupLyrics-Plus/assets/113321563/7d22adfa-3901-40d9-b385-384464de8ce8)

_Originally posted by @MetroHospitalsDev in https://github.com/Patrick-orz/PopupLyrics-Plus/issues/2#issuecomment-1926130538_

**Comment by Patrick-orz** [comment]
I would look into this further tomorrow, is the same issue occurring with other translation targets? (Disabling translations or translating into Chinese for instance)

**Comment by MetroHospitalsDev** [comment]
Processor Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz   1.19 GHz
Installed RAM	20.0 GB 
Edition Windows 11 Home Single Language Version	22H2
SSD 512GB

Target to other translation :
Google (English) : same like romanji , it make spotify frozen and using 100% CPU and 100% Memory
Chinese : Using 100% CPU and 100% memory , but when the lyrics shows it goes back to normal.
Romaji : Spotify froze , and using 100% CPU and 100 Memory
None Translation : Same like chinese , its using 100% CPU and 100% Memory, but when the lyrics show. goes back to normal
All the trial above happen when spotify not on active window

When spotify on active windows , everything works as intended without using 100% CPU and 100% Memory.

**Comment by Patrick-orz** [comment]
I still can't seem to reproduce the issue...  Check if my follow setup is correct

https://github.com/Patrick-orz/PopupLyrics-Plus/assets/132706084/93dca7af-38c1-4100-9da8-fa7287cf4775

I assume this issue isn't prevalent in all versions, can you tell me the latest commit without this issue?

**Comment by MetroHospitalsDev** [comment]
Sorry , After tried more attempt.
the issue will reproduce when spotify in minimized state.
but will goes back to normal when the lyrics finished load.


https://github.com/Patrick-orz/PopupLyrics-Plus/assets/113321563/d4586c3b-3518-481c-80d1-5698bcdfe26a

![spicetify](https://github.com/Patrick-orz/PopupLyrics-Plus/assets/113321563/f6cb3784-65bf-4d3d-86d7-d4bf280c3d96)

**Comment by Patrick-orz** [comment]
I was able to reproduce the issue :)! 

However, I don't think this is a problem on my extension specifically. I tested with the original spicetify [popuplyrics](https://github.com/spicetify/spicetify-cli/blob/master/Extensions/popupLyrics.js) plugin, same issue occurs (See below video). 

https://github.com/Patrick-orz/PopupLyrics-Plus/assets/132706084/50b2c5fe-1fc0-4872-a9d8-f7b72c370932

The issue is the most apparent when a song has "no lyrics", otherwise RAM & CPU goes up until the lyrics load (as you have described with my plugin as well). The issue is magnified on my modded version probably because of the extended "waiting" time due to the fetching from numerous APIs, causing RAM & CPU to be filled before lyrics actually load.

I would strongly recommend starting an issue on [spicetify-cli](https://github.com/spicetify/spicetify-cli), explaining this issue fully with reproduction procedures to the original devs (Pin me in the new issue if you start one). I would love if the spicetify team could patch this issue.

Thank you so much for reporting this . Meanwhile, you can try to just leave spotify open (unminized) as a workaround!

This thread would now be closed, and could be mentioned in your new issue within [spicetify-cli](https://github.com/spicetify/spicetify-cli)

**Comment by frallatta** [comment]
Hello , im already making the issue @Patrick-orz. https://github.com/spicetify/spicetify-cli/issues/2807#issue-2122304440

**Comment by Patrick-orz** [comment]
Newest version implemented official fix

**Comment by Orangy-Man** [comment]
sorry for the necro but ive posted on here before for a different issue but also referenced this. it still happens to be even though i redownloaded the extention

**Comment by Patrick-orz** [comment]
> sorry for the necro but ive posted on here before for a different issue but also referenced this. it still happens to be even though i redownloaded the extention

@Orangy-Man 
Sorry for the late response, I am on break. 

The freezing issue does indeed occur, which is weird, since the official extension seems to work smoothly when out of focus, and populyricsplus doesn't diverge from the original too much.

The issue only occurs for me (on mac) when I swipe to a desktop that doesn't contain the running spotify instance hosting the popuplyricsplus window. I assume you are on win from the screenshot you have posted in the different thread, but the environment required for such freezing to occur should be similar nevertheless.

I have a question and a possible **workaround** which I have mentioned in the previous thread.
- Does the original [popuplyrics](https://github.com/spicetify/cli/blob/main/Extensions/popupLyrics.js) extension freeze for you?
- **Potential Workaround** _If the original popuplyrics extension doesn't freeze_ : Try enabling popuplyricsplus and original popuplyrics at the same time (illustrated in the image below, left is popuplyricsplus and right is popuplyrics). Run original popuplyrics first then try popuplyricsplus. Although this sounds strange, this method has consistently resolved the issue on my end.
- If the original popuplyrics extension does freeze, you should probably file an issue in the official spicetify repo first.

<img width="201" alt="Screen Shot 2024-08-10 at 1 03 42 AM" src="https://github.com/user-attachments/assets/65c24c7d-ad1e-4d2d-a770-5df72121b54a">

This issue would stay closed unless the problem persists for you. _(I should really look into this weird freezing issue more in depth...)_

**Comment by Orangy-Man** [comment]
sorry for the extreamly late response, im not really paying attention to github since i dont use it much. Ive recoreded a little video of this glitch happening while im playing a game, im not 100% sure if this happens in any other of my games but since i was in minecraft at the time ill just use that as a base. this time, i only have popuplyrics plus. i was also playing on an online server if that adds anything 

https://github.com/user-attachments/assets/1068d2ee-9cd3-42f6-9a87-f7169d4198a2

**Comment by Patrick-orz** [comment]
I don't think this has anything to do with minecraft specifically, it's probably the fullscreen nature of the game. The video doesn't really help though, can you answer the questions in my previous post and try the proposed solutions?

> > sorry for the necro but ive posted on here before for a different issue but also referenced this. it still happens to be even though i redownloaded the extention
> 
> @Orangy-Man Sorry for the late response, I am on break.
> 
> The freezing issue does indeed occur, which is weird, since the official extension seems to work smoothly when out of focus, and populyricsplus doesn't diverge from the original too much.
> 
> The issue only occurs for me (on mac) when I swipe to a desktop that doesn't contain the running spotify instance hosting the popuplyricsplus window. I assume you are on win from the screenshot you have posted in the different thread, but the environment required for such freezing to occur should be similar nevertheless.
> 
> I have a question and a possible **workaround** which I have mentioned in the previous thread.
> 
> * Does the original [popuplyrics](https://github.com/spicetify/cli/blob/main/Extensions/popupLyrics.js) extension freeze for you?
> * **Potential Workaround** _If the original popuplyrics extension doesn't freeze_ : Try enabling popuplyricsplus and original popuplyrics at the same time (illustrated in the image below, left is popuplyricsplus and right is popuplyrics). Run original popuplyrics first then try popuplyricsplus. Although this sounds strange, this method has consistently resolved the issue on my end.
> * If the original popuplyrics extension does freeze, you should probably file an issue in the official spicetify repo first.
> 
> <img alt="Screen Shot 2024-08-10 at 1 03 42 AM" width="201" src="https://private-user-images.githubusercontent.com/132706084/356690542-65c24c7d-ad1e-4d2d-a770-5df72121b54a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NzEzNDUsIm5iZiI6MTcyMzk3MTA0NSwicGF0aCI6Ii8xMzI3MDYwODQvMzU2NjkwNTQyLTY1YzI0YzdkLWFkMWUtNGQyZC1hNzcwLTVkZjcyMTIxYjU0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQwODUwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTBkMzhhM2NhMTZiYTNjNDg2N2IwMzI4MGI2OGRjOTEyZjBhYmFkMzcwZTRhMTA0MzI4MWNmMzk4ZmRkZjEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M2hto1WtUVz186TNUeibpiq8VZexgH1FWUqtJZVOvmw">
> This issue would stay closed unless the problem persists for you. _(I should really look into this weird freezing issue more in depth...)_

**Comment by Orangy-Man** [comment]
> I don't think this has anything to do with minecraft specifically, it's probably the fullscreen nature of the game. The video doesn't really help though, can you answer the questions in my previous post and try the proposed solutions?
> 
> > > sorry for the necro but ive posted on here before for a different issue but also referenced this. it still happens to be even though i redownloaded the extention
> > 
> > 
> > @Orangy-Man Sorry for the late response, I am on break.
> > The freezing issue does indeed occur, which is weird, since the official extension seems to work smoothly when out of focus, and populyricsplus doesn't diverge from the original too much.
> > The issue only occurs for me (on mac) when I swipe to a desktop that doesn't contain the running spotify instance hosting the popuplyricsplus window. I assume you are on win from the screenshot you have posted in the different thread, but the environment required for such freezing to occur should be similar nevertheless.
> > I have a question and a possible **workaround** which I have mentioned in the previous thread.
> > 
> > * Does the original [popuplyrics](https://github.com/spicetify/cli/blob/main/Extensions/popupLyrics.js) extension freeze for you?
> > * **Potential Workaround** _If the original popuplyrics extension doesn't freeze_ : Try enabling popuplyricsplus and original popuplyrics at the same time (illustrated in the image below, left is popuplyricsplus and right is popuplyrics). Run original popuplyrics first then try popuplyricsplus. Although this sounds strange, this method has consistently resolved the issue on my end.
> > * If the original popuplyrics extension does freeze, you should probably file an issue in the official spicetify repo first.
> > 
> > <img alt="Screen Shot 2024-08-10 at 1 03 42 AM" width="201" src="https://private-user-images.githubusercontent.com/132706084/356690542-65c24c7d-ad1e-4d2d-a770-5df72121b54a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NzEzNDUsIm5iZiI6MTcyMzk3MTA0NSwicGF0aCI6Ii8xMzI3MDYwODQvMzU2NjkwNTQyLTY1YzI0YzdkLWFkMWUtNGQyZC1hNzcwLTVkZjcyMTIxYjU0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQwODUwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTBkMzhhM2NhMTZiYTNjNDg2N2IwMzI4MGI2OGRjOTEyZjBhYmFkMzcwZTRhMTA0MzI4MWNmMzk4ZmRkZjEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M2hto1WtUVz186TNUeibpiq8VZexgH1FWUqtJZVOvmw">
> > This issue would stay closed unless the problem persists for you. _(I should really look into this weird freezing issue more in depth...)_

iirc, the orignal one also froze and thats why i looked for an alternative in the first place. and for the workaround, i will test that now and then get back to you

**Comment by Orangy-Man** [comment]
also

> I don't think this has anything to do with minecraft specifically, it's probably the fullscreen nature of the game. The video doesn't really help though, can you answer the questions in my previous post and try the proposed solutions?

i have a mod that adds borderless windowed mode so im not sure that would be the issue. it works sometimes but not all the time

**Comment by Orangy-Man** [comment]
ok i just got done testing both. At least today, they both scroll but the scrolling is very slow.

**Comment by Patrick-orz** [comment]
If the original doesn't scroll, please submit an issue to the original spicetify repo as I have mentioned.

> ok i just got done testing both. At least today, they both scroll but the scrolling is very slow.

I assume the freezing issue doesn't appear from the phrase "they both scroll". I don't understand what you mean by "the scrolling is very slow" though. Please elaborate.

**Comment by Orangy-Man** [comment]
> If the original doesn't scroll, please submit an issue to the original spicetify repo as I have mentioned.
> 
> > ok i just got done testing both. At least today, they both scroll but the scrolling is very slow.
> 
> I assume the freezing issue doesn't appear from the phrase "they both scroll". I don't understand what you mean by "the scrolling is very slow" though. Please elaborate.

by "scroll slowly" i meant that they are buffering a lot, like its having trouble with something

**Comment by Patrick-orz** [comment]
That is still a vague description, please send a video to illustrate (include the behavior of both original PopupLyrics and PopupLyricsPlus).

**Comment by Orangy-Man** [comment]
> That is still a vague description, please send a video to illustrate (include the behavior of both original PopupLyrics and PopupLyricsPlus).

on the off chance i do get the lyrics to scroll, this is what i meant by it going slowly


https://github.com/user-attachments/assets/6199f171-e78b-4a00-9489-f4fece6b435c

**Comment by Patrick-orz** [comment]
I see no issue in the video, it is the expected behaviour for both PopupLyrics and PopupLyricsPlus (the lyrics scroll in sync with the song playing).

**If both PopupLyrics and PopupLyricsPlus freeze from time to time, I again suggest reporting the issue in the official spicetify repo first in order to have PopupLyrics functioning correctly for you first.**

If only PopupLyricsPlus dysfunctions, even with my proposed workaround, I will try to pinpoint the core of the issue.
