### ISSUE TITLE
Apostrophes and commas have a space before or after when it comes to English songs

### ISSUE THREAD

**Issue by yannoulis** [Patrick-orz/PopupLyrics-Plus#6]
Weird space with these characters
![image](https://github.com/Patrick-orz/PopupLyrics-Plus/assets/148008593/755c4a26-3034-4d96-a09d-8be07a7c3231)

**Comment by Patrick-orz** [comment]
Will look into it, is this through translations into english or originally english lyrics? Which song is this?

**Comment by yannoulis** [comment]
It's originally English lyrics. Song is Floating (Feat. Khalid) - Alina Baraz. This is how the lyrics originally look like
![image](https://github.com/Patrick-orz/PopupLyrics-Plus/assets/148008593/832ddac3-a989-4848-831f-9e2e08571fb7)

**Comment by Patrick-orz** [comment]
The lyrics seem fine with me, I assume it's an issue with all apostrophes and commas.
<img width="364" alt="Screen Shot 2024-03-07 at 3 04 34 PM" src="https://github.com/Patrick-orz/PopupLyrics-Plus/assets/132706084/9503d2b7-19e0-4ca6-9544-877378ad352d">

PopupLyricsPlus settings
<img width="423" alt="Screen Shot 2024-03-07 at 3 06 59 PM" src="https://github.com/Patrick-orz/PopupLyrics-Plus/assets/132706084/4ee11bef-d1a7-4aa9-9fbe-4099be60fd2d">

<img width="420" alt="Screen Shot 2024-03-07 at 3 08 58 PM" src="https://github.com/Patrick-orz/PopupLyrics-Plus/assets/132706084/b9860629-0482-4297-90ab-396699279437">

I'm on mac currently.

Tell me if there are any inconsistencies with your settings and mine.

**Comment by yannoulis** [comment]
It seems the apostrophes and commas only get separated when the lyrics are translated to romaji.
This is when it's translating to Romaji
![image](https://github.com/Patrick-orz/PopupLyrics-Plus/assets/148008593/213dcfa5-57a7-43a8-b7b2-327b29b8c0d5)

This is when it's translating to none
![image](https://github.com/Patrick-orz/PopupLyrics-Plus/assets/148008593/44ef78eb-b506-4b09-aee3-5b9689775c17)

It also happens to translated songs that aren't English in the first place, this is the case with quotation marks in the song.
![image](https://github.com/Patrick-orz/PopupLyrics-Plus/assets/148008593/873074fd-e9e2-4bd3-afa4-9cd263b8bfca)

**Comment by Patrick-orz** [comment]
This should be resolved in the latest commit. Romajify is intended to be used only on Japanese lyrics, but a hard fix is implemented anyways so english lyrics appear normal.

Sorry for a somewhat late fix, I was travelling :)
